// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XDISPARITY_PIXEL_COPROCESSOR_H
#define XDISPARITY_PIXEL_COPROCESSOR_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xdisparity_pixel_coprocessor_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_bus_BaseAddress;
    u32 Axilites_BaseAddress;
} XDisparity_pixel_coprocessor_Config;
#endif

typedef struct {
    u32 Ctrl_bus_BaseAddress;
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XDisparity_pixel_coprocessor;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XDisparity_pixel_coprocessor_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XDisparity_pixel_coprocessor_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XDisparity_pixel_coprocessor_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XDisparity_pixel_coprocessor_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XDisparity_pixel_coprocessor_Initialize(XDisparity_pixel_coprocessor *InstancePtr, u16 DeviceId);
XDisparity_pixel_coprocessor_Config* XDisparity_pixel_coprocessor_LookupConfig(u16 DeviceId);
int XDisparity_pixel_coprocessor_CfgInitialize(XDisparity_pixel_coprocessor *InstancePtr, XDisparity_pixel_coprocessor_Config *ConfigPtr);
#else
int XDisparity_pixel_coprocessor_Initialize(XDisparity_pixel_coprocessor *InstancePtr, const char* InstanceName);
int XDisparity_pixel_coprocessor_Release(XDisparity_pixel_coprocessor *InstancePtr);
#endif

void XDisparity_pixel_coprocessor_Start(XDisparity_pixel_coprocessor *InstancePtr);
u32 XDisparity_pixel_coprocessor_IsDone(XDisparity_pixel_coprocessor *InstancePtr);
u32 XDisparity_pixel_coprocessor_IsIdle(XDisparity_pixel_coprocessor *InstancePtr);
u32 XDisparity_pixel_coprocessor_IsReady(XDisparity_pixel_coprocessor *InstancePtr);
void XDisparity_pixel_coprocessor_EnableAutoRestart(XDisparity_pixel_coprocessor *InstancePtr);
void XDisparity_pixel_coprocessor_DisableAutoRestart(XDisparity_pixel_coprocessor *InstancePtr);
u32 XDisparity_pixel_coprocessor_Get_return(XDisparity_pixel_coprocessor *InstancePtr);

void XDisparity_pixel_coprocessor_Set_bpp(XDisparity_pixel_coprocessor *InstancePtr, u32 Data);
u32 XDisparity_pixel_coprocessor_Get_bpp(XDisparity_pixel_coprocessor *InstancePtr);
void XDisparity_pixel_coprocessor_Set_xDim(XDisparity_pixel_coprocessor *InstancePtr, u32 Data);
u32 XDisparity_pixel_coprocessor_Get_xDim(XDisparity_pixel_coprocessor *InstancePtr);
void XDisparity_pixel_coprocessor_Set_yDim(XDisparity_pixel_coprocessor *InstancePtr, u32 Data);
u32 XDisparity_pixel_coprocessor_Get_yDim(XDisparity_pixel_coprocessor *InstancePtr);
u32 XDisparity_pixel_coprocessor_Get_current_row(XDisparity_pixel_coprocessor *InstancePtr);
u32 XDisparity_pixel_coprocessor_Get_current_row_vld(XDisparity_pixel_coprocessor *InstancePtr);
void XDisparity_pixel_coprocessor_Set_maxDisparity(XDisparity_pixel_coprocessor *InstancePtr, u32 Data);
u32 XDisparity_pixel_coprocessor_Get_maxDisparity(XDisparity_pixel_coprocessor *InstancePtr);
void XDisparity_pixel_coprocessor_Set_addrLeft(XDisparity_pixel_coprocessor *InstancePtr, u32 Data);
u32 XDisparity_pixel_coprocessor_Get_addrLeft(XDisparity_pixel_coprocessor *InstancePtr);
void XDisparity_pixel_coprocessor_Set_addrRight(XDisparity_pixel_coprocessor *InstancePtr, u32 Data);
u32 XDisparity_pixel_coprocessor_Get_addrRight(XDisparity_pixel_coprocessor *InstancePtr);
void XDisparity_pixel_coprocessor_Set_addrOutput(XDisparity_pixel_coprocessor *InstancePtr, u32 Data);
u32 XDisparity_pixel_coprocessor_Get_addrOutput(XDisparity_pixel_coprocessor *InstancePtr);

void XDisparity_pixel_coprocessor_InterruptGlobalEnable(XDisparity_pixel_coprocessor *InstancePtr);
void XDisparity_pixel_coprocessor_InterruptGlobalDisable(XDisparity_pixel_coprocessor *InstancePtr);
void XDisparity_pixel_coprocessor_InterruptEnable(XDisparity_pixel_coprocessor *InstancePtr, u32 Mask);
void XDisparity_pixel_coprocessor_InterruptDisable(XDisparity_pixel_coprocessor *InstancePtr, u32 Mask);
void XDisparity_pixel_coprocessor_InterruptClear(XDisparity_pixel_coprocessor *InstancePtr, u32 Mask);
u32 XDisparity_pixel_coprocessor_InterruptGetEnabled(XDisparity_pixel_coprocessor *InstancePtr);
u32 XDisparity_pixel_coprocessor_InterruptGetStatus(XDisparity_pixel_coprocessor *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
