# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sefo/devel/dev_boards/zedBoard/self-backed/hdl/projects/adv7511/zed/adv7511_zed.srcs/sources_1/ip/image_filter_0/image_filter_0.xci
# IP: The module: 'image_filter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sefo/devel/dev_boards/zedBoard/self-backed/hdl/projects/adv7511/zed/adv7511_zed.srcs/sources_1/ip/image_filter_0/constraints/image_filter.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_filter_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/sefo/devel/dev_boards/zedBoard/self-backed/hdl/projects/adv7511/zed/adv7511_zed.srcs/sources_1/ip/image_filter_0/constraints/image_filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_filter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/sefo/devel/dev_boards/zedBoard/self-backed/hdl/projects/adv7511/zed/adv7511_zed.srcs/sources_1/ip/image_filter_0/image_filter_0.xci
# IP: The module: 'image_filter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sefo/devel/dev_boards/zedBoard/self-backed/hdl/projects/adv7511/zed/adv7511_zed.srcs/sources_1/ip/image_filter_0/constraints/image_filter.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_filter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/sefo/devel/dev_boards/zedBoard/self-backed/hdl/projects/adv7511/zed/adv7511_zed.srcs/sources_1/ip/image_filter_0/constraints/image_filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_filter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
