// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// CTRL_BUS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of bpp
//        bit 7~0 - bpp[7:0] (Read/Write)
//        others  - reserved
// 0x14 : reserved
// 0x18 : Data signal of xDim
//        bit 31~0 - xDim[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of yDim
//        bit 31~0 - yDim[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of current_row
//        bit 31~0 - current_row[31:0] (Read)
// 0x2c : Control signal of current_row
//        bit 0  - current_row_ap_vld (Read/COR)
//        others - reserved
// 0x30 : Data signal of maxDisparity
//        bit 31~0 - maxDisparity[31:0] (Read/Write)
// 0x34 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDISPARITY_PIXEL_COPROCESSOR_CTRL_BUS_ADDR_BPP_DATA          0x10
#define XDISPARITY_PIXEL_COPROCESSOR_CTRL_BUS_BITS_BPP_DATA          8
#define XDISPARITY_PIXEL_COPROCESSOR_CTRL_BUS_ADDR_XDIM_DATA         0x18
#define XDISPARITY_PIXEL_COPROCESSOR_CTRL_BUS_BITS_XDIM_DATA         32
#define XDISPARITY_PIXEL_COPROCESSOR_CTRL_BUS_ADDR_YDIM_DATA         0x20
#define XDISPARITY_PIXEL_COPROCESSOR_CTRL_BUS_BITS_YDIM_DATA         32
#define XDISPARITY_PIXEL_COPROCESSOR_CTRL_BUS_ADDR_CURRENT_ROW_DATA  0x28
#define XDISPARITY_PIXEL_COPROCESSOR_CTRL_BUS_BITS_CURRENT_ROW_DATA  32
#define XDISPARITY_PIXEL_COPROCESSOR_CTRL_BUS_ADDR_CURRENT_ROW_CTRL  0x2c
#define XDISPARITY_PIXEL_COPROCESSOR_CTRL_BUS_ADDR_MAXDISPARITY_DATA 0x30
#define XDISPARITY_PIXEL_COPROCESSOR_CTRL_BUS_BITS_MAXDISPARITY_DATA 32

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ap_return
//        bit 31~0 - ap_return[31:0] (Read)
// 0x18 : Data signal of addrLeft
//        bit 31~0 - addrLeft[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of addrRight
//        bit 31~0 - addrRight[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of addrOutput
//        bit 31~0 - addrOutput[31:0] (Read/Write)
// 0x2c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDISPARITY_PIXEL_COPROCESSOR_AXILITES_ADDR_AP_CTRL         0x00
#define XDISPARITY_PIXEL_COPROCESSOR_AXILITES_ADDR_GIE             0x04
#define XDISPARITY_PIXEL_COPROCESSOR_AXILITES_ADDR_IER             0x08
#define XDISPARITY_PIXEL_COPROCESSOR_AXILITES_ADDR_ISR             0x0c
#define XDISPARITY_PIXEL_COPROCESSOR_AXILITES_ADDR_AP_RETURN       0x10
#define XDISPARITY_PIXEL_COPROCESSOR_AXILITES_BITS_AP_RETURN       32
#define XDISPARITY_PIXEL_COPROCESSOR_AXILITES_ADDR_ADDRLEFT_DATA   0x18
#define XDISPARITY_PIXEL_COPROCESSOR_AXILITES_BITS_ADDRLEFT_DATA   32
#define XDISPARITY_PIXEL_COPROCESSOR_AXILITES_ADDR_ADDRRIGHT_DATA  0x20
#define XDISPARITY_PIXEL_COPROCESSOR_AXILITES_BITS_ADDRRIGHT_DATA  32
#define XDISPARITY_PIXEL_COPROCESSOR_AXILITES_ADDR_ADDROUTPUT_DATA 0x28
#define XDISPARITY_PIXEL_COPROCESSOR_AXILITES_BITS_ADDROUTPUT_DATA 32

