// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmorphological_filter.h"

extern XMorphological_filter_Config XMorphological_filter_ConfigTable[];

XMorphological_filter_Config *XMorphological_filter_LookupConfig(u16 DeviceId) {
	XMorphological_filter_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMORPHOLOGICAL_FILTER_NUM_INSTANCES; Index++) {
		if (XMorphological_filter_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMorphological_filter_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMorphological_filter_Initialize(XMorphological_filter *InstancePtr, u16 DeviceId) {
	XMorphological_filter_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMorphological_filter_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMorphological_filter_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

