// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XMORPHOLOGICAL_FILTER_H
#define XMORPHOLOGICAL_FILTER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmorphological_filter_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XMorphological_filter_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XMorphological_filter;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMorphological_filter_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMorphological_filter_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMorphological_filter_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMorphological_filter_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMorphological_filter_Initialize(XMorphological_filter *InstancePtr, u16 DeviceId);
XMorphological_filter_Config* XMorphological_filter_LookupConfig(u16 DeviceId);
int XMorphological_filter_CfgInitialize(XMorphological_filter *InstancePtr, XMorphological_filter_Config *ConfigPtr);
#else
int XMorphological_filter_Initialize(XMorphological_filter *InstancePtr, const char* InstanceName);
int XMorphological_filter_Release(XMorphological_filter *InstancePtr);
#endif

void XMorphological_filter_Start(XMorphological_filter *InstancePtr);
u32 XMorphological_filter_IsDone(XMorphological_filter *InstancePtr);
u32 XMorphological_filter_IsIdle(XMorphological_filter *InstancePtr);
u32 XMorphological_filter_IsReady(XMorphological_filter *InstancePtr);
void XMorphological_filter_EnableAutoRestart(XMorphological_filter *InstancePtr);
void XMorphological_filter_DisableAutoRestart(XMorphological_filter *InstancePtr);

void XMorphological_filter_Set_rows(XMorphological_filter *InstancePtr, u32 Data);
u32 XMorphological_filter_Get_rows(XMorphological_filter *InstancePtr);
void XMorphological_filter_Set_cols(XMorphological_filter *InstancePtr, u32 Data);
u32 XMorphological_filter_Get_cols(XMorphological_filter *InstancePtr);

void XMorphological_filter_InterruptGlobalEnable(XMorphological_filter *InstancePtr);
void XMorphological_filter_InterruptGlobalDisable(XMorphological_filter *InstancePtr);
void XMorphological_filter_InterruptEnable(XMorphological_filter *InstancePtr, u32 Mask);
void XMorphological_filter_InterruptDisable(XMorphological_filter *InstancePtr, u32 Mask);
void XMorphological_filter_InterruptClear(XMorphological_filter *InstancePtr, u32 Mask);
u32 XMorphological_filter_InterruptGetEnabled(XMorphological_filter *InstancePtr);
u32 XMorphological_filter_InterruptGetStatus(XMorphological_filter *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
