// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmorphological_filter.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMorphological_filter_CfgInitialize(XMorphological_filter *InstancePtr, XMorphological_filter_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMorphological_filter_Start(XMorphological_filter *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMorphological_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XMorphological_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMorphological_filter_IsDone(XMorphological_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMorphological_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMorphological_filter_IsIdle(XMorphological_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMorphological_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMorphological_filter_IsReady(XMorphological_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMorphological_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMorphological_filter_EnableAutoRestart(XMorphological_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMorphological_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XMorphological_filter_DisableAutoRestart(XMorphological_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMorphological_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XMorphological_filter_Set_rows(XMorphological_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMorphological_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XMorphological_filter_Get_rows(XMorphological_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMorphological_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XMorphological_filter_Set_cols(XMorphological_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMorphological_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XMorphological_filter_Get_cols(XMorphological_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMorphological_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XMorphological_filter_InterruptGlobalEnable(XMorphological_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMorphological_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_GIE, 1);
}

void XMorphological_filter_InterruptGlobalDisable(XMorphological_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMorphological_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_GIE, 0);
}

void XMorphological_filter_InterruptEnable(XMorphological_filter *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMorphological_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_IER);
    XMorphological_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XMorphological_filter_InterruptDisable(XMorphological_filter *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMorphological_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_IER);
    XMorphological_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XMorphological_filter_InterruptClear(XMorphological_filter *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMorphological_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XMorphological_filter_InterruptGetEnabled(XMorphological_filter *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMorphological_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_IER);
}

u32 XMorphological_filter_InterruptGetStatus(XMorphological_filter *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMorphological_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XMORPHOLOGICAL_FILTER_CONTROL_BUS_ADDR_ISR);
}

