// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSTEREO_MATCHER_H
#define XSTEREO_MATCHER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xstereo_matcher_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XStereo_matcher_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XStereo_matcher;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XStereo_matcher_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XStereo_matcher_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XStereo_matcher_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XStereo_matcher_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XStereo_matcher_Initialize(XStereo_matcher *InstancePtr, u16 DeviceId);
XStereo_matcher_Config* XStereo_matcher_LookupConfig(u16 DeviceId);
int XStereo_matcher_CfgInitialize(XStereo_matcher *InstancePtr, XStereo_matcher_Config *ConfigPtr);
#else
int XStereo_matcher_Initialize(XStereo_matcher *InstancePtr, const char* InstanceName);
int XStereo_matcher_Release(XStereo_matcher *InstancePtr);
#endif

void XStereo_matcher_Start(XStereo_matcher *InstancePtr);
u32 XStereo_matcher_IsDone(XStereo_matcher *InstancePtr);
u32 XStereo_matcher_IsIdle(XStereo_matcher *InstancePtr);
u32 XStereo_matcher_IsReady(XStereo_matcher *InstancePtr);
void XStereo_matcher_EnableAutoRestart(XStereo_matcher *InstancePtr);
void XStereo_matcher_DisableAutoRestart(XStereo_matcher *InstancePtr);

void XStereo_matcher_Set_rows(XStereo_matcher *InstancePtr, u32 Data);
u32 XStereo_matcher_Get_rows(XStereo_matcher *InstancePtr);
void XStereo_matcher_Set_cols(XStereo_matcher *InstancePtr, u32 Data);
u32 XStereo_matcher_Get_cols(XStereo_matcher *InstancePtr);

void XStereo_matcher_InterruptGlobalEnable(XStereo_matcher *InstancePtr);
void XStereo_matcher_InterruptGlobalDisable(XStereo_matcher *InstancePtr);
void XStereo_matcher_InterruptEnable(XStereo_matcher *InstancePtr, u32 Mask);
void XStereo_matcher_InterruptDisable(XStereo_matcher *InstancePtr, u32 Mask);
void XStereo_matcher_InterruptClear(XStereo_matcher *InstancePtr, u32 Mask);
u32 XStereo_matcher_InterruptGetEnabled(XStereo_matcher *InstancePtr);
u32 XStereo_matcher_InterruptGetStatus(XStereo_matcher *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
