// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xa0_stereo_matcher.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XA0_stereo_matcher_CfgInitialize(XA0_stereo_matcher *InstancePtr, XA0_stereo_matcher_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XA0_stereo_matcher_Start(XA0_stereo_matcher *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XA0_stereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XA0_stereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XA0_stereo_matcher_IsDone(XA0_stereo_matcher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XA0_stereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XA0_stereo_matcher_IsIdle(XA0_stereo_matcher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XA0_stereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XA0_stereo_matcher_IsReady(XA0_stereo_matcher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XA0_stereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XA0_stereo_matcher_EnableAutoRestart(XA0_stereo_matcher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XA0_stereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XA0_stereo_matcher_DisableAutoRestart(XA0_stereo_matcher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XA0_stereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XA0_stereo_matcher_Set_rows(XA0_stereo_matcher *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XA0_stereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XA0_stereo_matcher_Get_rows(XA0_stereo_matcher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XA0_stereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XA0_stereo_matcher_Set_cols(XA0_stereo_matcher *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XA0_stereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XA0_stereo_matcher_Get_cols(XA0_stereo_matcher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XA0_stereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XA0_stereo_matcher_InterruptGlobalEnable(XA0_stereo_matcher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XA0_stereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_GIE, 1);
}

void XA0_stereo_matcher_InterruptGlobalDisable(XA0_stereo_matcher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XA0_stereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_GIE, 0);
}

void XA0_stereo_matcher_InterruptEnable(XA0_stereo_matcher *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XA0_stereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_IER);
    XA0_stereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XA0_stereo_matcher_InterruptDisable(XA0_stereo_matcher *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XA0_stereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_IER);
    XA0_stereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XA0_stereo_matcher_InterruptClear(XA0_stereo_matcher *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XA0_stereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XA0_stereo_matcher_InterruptGetEnabled(XA0_stereo_matcher *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XA0_stereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_IER);
}

u32 XA0_stereo_matcher_InterruptGetStatus(XA0_stereo_matcher *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XA0_stereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XA0_STEREO_MATCHER_CONTROL_BUS_ADDR_ISR);
}

