// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XA0_STEREO_MATCHER_H
#define XA0_STEREO_MATCHER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xa0_stereo_matcher_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XA0_stereo_matcher_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XA0_stereo_matcher;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XA0_stereo_matcher_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XA0_stereo_matcher_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XA0_stereo_matcher_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XA0_stereo_matcher_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XA0_stereo_matcher_Initialize(XA0_stereo_matcher *InstancePtr, u16 DeviceId);
XA0_stereo_matcher_Config* XA0_stereo_matcher_LookupConfig(u16 DeviceId);
int XA0_stereo_matcher_CfgInitialize(XA0_stereo_matcher *InstancePtr, XA0_stereo_matcher_Config *ConfigPtr);
#else
int XA0_stereo_matcher_Initialize(XA0_stereo_matcher *InstancePtr, const char* InstanceName);
int XA0_stereo_matcher_Release(XA0_stereo_matcher *InstancePtr);
#endif

void XA0_stereo_matcher_Start(XA0_stereo_matcher *InstancePtr);
u32 XA0_stereo_matcher_IsDone(XA0_stereo_matcher *InstancePtr);
u32 XA0_stereo_matcher_IsIdle(XA0_stereo_matcher *InstancePtr);
u32 XA0_stereo_matcher_IsReady(XA0_stereo_matcher *InstancePtr);
void XA0_stereo_matcher_EnableAutoRestart(XA0_stereo_matcher *InstancePtr);
void XA0_stereo_matcher_DisableAutoRestart(XA0_stereo_matcher *InstancePtr);

void XA0_stereo_matcher_Set_rows(XA0_stereo_matcher *InstancePtr, u32 Data);
u32 XA0_stereo_matcher_Get_rows(XA0_stereo_matcher *InstancePtr);
void XA0_stereo_matcher_Set_cols(XA0_stereo_matcher *InstancePtr, u32 Data);
u32 XA0_stereo_matcher_Get_cols(XA0_stereo_matcher *InstancePtr);

void XA0_stereo_matcher_InterruptGlobalEnable(XA0_stereo_matcher *InstancePtr);
void XA0_stereo_matcher_InterruptGlobalDisable(XA0_stereo_matcher *InstancePtr);
void XA0_stereo_matcher_InterruptEnable(XA0_stereo_matcher *InstancePtr, u32 Mask);
void XA0_stereo_matcher_InterruptDisable(XA0_stereo_matcher *InstancePtr, u32 Mask);
void XA0_stereo_matcher_InterruptClear(XA0_stereo_matcher *InstancePtr, u32 Mask);
u32 XA0_stereo_matcher_InterruptGetEnabled(XA0_stereo_matcher *InstancePtr);
u32 XA0_stereo_matcher_InterruptGetStatus(XA0_stereo_matcher *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
