// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xa0_stereo_matcher.h"

extern XA0_stereo_matcher_Config XA0_stereo_matcher_ConfigTable[];

XA0_stereo_matcher_Config *XA0_stereo_matcher_LookupConfig(u16 DeviceId) {
	XA0_stereo_matcher_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XA0_STEREO_MATCHER_NUM_INSTANCES; Index++) {
		if (XA0_stereo_matcher_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XA0_stereo_matcher_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XA0_stereo_matcher_Initialize(XA0_stereo_matcher *InstancePtr, u16 DeviceId) {
	XA0_stereo_matcher_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XA0_stereo_matcher_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XA0_stereo_matcher_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

