// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module morphological_filter_AXIvideo2Mat_8_720_1280_0_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        video_in_TDATA,
        video_in_TVALID,
        video_in_TREADY,
        video_in_TKEEP,
        video_in_TSTRB,
        video_in_TUSER,
        video_in_TLAST,
        video_in_TID,
        video_in_TDEST,
        rows,
        cols,
        img_data_stream_V_din,
        img_data_stream_V_full_n,
        img_data_stream_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 7'b1;
parameter    ap_ST_st2_fsm_1 = 7'b10;
parameter    ap_ST_st3_fsm_2 = 7'b100;
parameter    ap_ST_st4_fsm_3 = 7'b1000;
parameter    ap_ST_pp1_stg0_fsm_4 = 7'b10000;
parameter    ap_ST_st7_fsm_5 = 7'b100000;
parameter    ap_ST_st8_fsm_6 = 7'b1000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] video_in_TDATA;
input   video_in_TVALID;
output   video_in_TREADY;
input  [0:0] video_in_TKEEP;
input  [0:0] video_in_TSTRB;
input  [0:0] video_in_TUSER;
input  [0:0] video_in_TLAST;
input  [0:0] video_in_TID;
input  [0:0] video_in_TDEST;
input  [9:0] rows;
input  [10:0] cols;
output  [7:0] img_data_stream_V_din;
input   img_data_stream_V_full_n;
output   img_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg video_in_TREADY;
reg img_data_stream_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm = 7'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_26;
reg   [0:0] eol_reg_160;
reg   [7:0] axi_data_V_1_i_reg_171;
reg   [10:0] p_2_i_reg_182;
reg   [0:0] eol_i_reg_193;
reg   [0:0] axi_last_V_2_i_reg_205;
reg   [7:0] p_Val2_s_reg_218;
reg    ap_sig_bdd_65;
reg   [7:0] tmp_data_V_reg_330;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_77;
reg   [0:0] tmp_last_V_reg_338;
wire   [0:0] exitcond2_i_fu_284_p2;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_91;
wire   [9:0] i_V_fu_289_p2;
reg   [9:0] i_V_reg_354;
wire   [0:0] exitcond_i_fu_295_p2;
reg   [0:0] exitcond_i_reg_359;
reg    ap_sig_cseq_ST_pp1_stg0_fsm_4;
reg    ap_sig_bdd_102;
wire   [0:0] brmerge_i_fu_309_p2;
reg    ap_sig_bdd_110;
reg    ap_reg_ppiten_pp1_it0 = 1'b0;
reg    ap_sig_bdd_117;
reg    ap_reg_ppiten_pp1_it1 = 1'b0;
wire   [10:0] j_V_fu_300_p2;
reg    ap_sig_cseq_ST_st7_fsm_5;
reg    ap_sig_bdd_136;
reg    ap_sig_bdd_141;
reg   [0:0] axi_last_V_3_i_reg_231;
reg   [0:0] axi_last_V1_i_reg_129;
reg    ap_sig_cseq_ST_st8_fsm_6;
reg    ap_sig_bdd_159;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_166;
reg   [7:0] axi_data_V_3_i_reg_243;
reg   [7:0] axi_data_V1_i_reg_139;
reg   [9:0] p_i_reg_149;
reg   [0:0] eol_phi_fu_163_p4;
reg   [7:0] axi_data_V_1_i_phi_fu_174_p4;
reg   [0:0] eol_i_phi_fu_197_p4;
wire   [0:0] ap_reg_phiprechg_axi_last_V_2_i_reg_205pp1_it0;
wire   [7:0] ap_reg_phiprechg_p_Val2_s_reg_218pp1_it0;
reg   [0:0] eol_2_i_reg_255;
reg   [0:0] sof_1_i_fu_88;
wire   [0:0] tmp_user_V_fu_275_p1;
reg   [6:0] ap_NS_fsm;
reg    ap_sig_bdd_109;
reg    ap_sig_bdd_190;
reg    ap_sig_bdd_128;




always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond2_i_fu_284_p2 == ap_const_lv1_0))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond_i_fu_295_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond2_i_fu_284_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond_i_fu_295_p2 == ap_const_lv1_0) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond2_i_fu_284_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond_i_fu_295_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        axi_data_V1_i_reg_139 <= tmp_data_V_reg_330;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        axi_data_V1_i_reg_139 <= axi_data_V_3_i_reg_243;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond_i_reg_359 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        axi_data_V_1_i_reg_171 <= p_Val2_s_reg_218;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond2_i_fu_284_p2 == ap_const_lv1_0))) begin
        axi_data_V_1_i_reg_171 <= axi_data_V1_i_reg_139;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond_i_fu_295_p2 == ap_const_lv1_0))) begin
        axi_data_V_3_i_reg_243 <= axi_data_V_1_i_phi_fu_174_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_i_reg_255) & ~ap_sig_bdd_141)) begin
        axi_data_V_3_i_reg_243 <= video_in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        axi_last_V1_i_reg_129 <= tmp_last_V_reg_338;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        axi_last_V1_i_reg_129 <= axi_last_V_3_i_reg_231;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_bdd_128) begin
        if (ap_sig_bdd_190) begin
            axi_last_V_2_i_reg_205 <= eol_phi_fu_163_p4;
        end else if (ap_sig_bdd_109) begin
            axi_last_V_2_i_reg_205 <= video_in_TLAST;
        end else if ((ap_true == ap_true)) begin
            axi_last_V_2_i_reg_205 <= ap_reg_phiprechg_axi_last_V_2_i_reg_205pp1_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond_i_fu_295_p2 == ap_const_lv1_0))) begin
        axi_last_V_3_i_reg_231 <= eol_phi_fu_163_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_i_reg_255) & ~ap_sig_bdd_141)) begin
        axi_last_V_3_i_reg_231 <= video_in_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond_i_fu_295_p2 == ap_const_lv1_0))) begin
        eol_2_i_reg_255 <= eol_i_phi_fu_197_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_i_reg_255) & ~ap_sig_bdd_141)) begin
        eol_2_i_reg_255 <= video_in_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond_i_reg_359 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        eol_i_reg_193 <= axi_last_V_2_i_reg_205;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond2_i_fu_284_p2 == ap_const_lv1_0))) begin
        eol_i_reg_193 <= ap_const_lv1_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond_i_reg_359 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        eol_reg_160 <= axi_last_V_2_i_reg_205;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond2_i_fu_284_p2 == ap_const_lv1_0))) begin
        eol_reg_160 <= axi_last_V1_i_reg_129;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond_i_fu_295_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        p_2_i_reg_182 <= j_V_fu_300_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond2_i_fu_284_p2 == ap_const_lv1_0))) begin
        p_2_i_reg_182 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_bdd_128) begin
        if (ap_sig_bdd_190) begin
            p_Val2_s_reg_218 <= axi_data_V_1_i_phi_fu_174_p4;
        end else if (ap_sig_bdd_109) begin
            p_Val2_s_reg_218 <= video_in_TDATA;
        end else if ((ap_true == ap_true)) begin
            p_Val2_s_reg_218 <= ap_reg_phiprechg_p_Val2_s_reg_218pp1_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        p_i_reg_149 <= ap_const_lv10_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        p_i_reg_149 <= i_V_reg_354;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond_i_fu_295_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        sof_1_i_fu_88 <= ap_const_lv1_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        sof_1_i_fu_88 <= ap_const_lv1_1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        exitcond_i_reg_359 <= exitcond_i_fu_295_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        i_V_reg_354 <= i_V_fu_289_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(video_in_TVALID == ap_const_logic_0))) begin
        tmp_data_V_reg_330 <= video_in_TDATA;
        tmp_last_V_reg_338 <= video_in_TLAST;
    end
end

always @ (ap_done_reg or exitcond2_i_fu_284_p2 or ap_sig_cseq_ST_st4_fsm_3) begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond2_i_fu_284_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (exitcond2_i_fu_284_p2 or ap_sig_cseq_ST_st4_fsm_3) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond2_i_fu_284_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_102) begin
    if (ap_sig_bdd_102) begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_26) begin
    if (ap_sig_bdd_26) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_77) begin
    if (ap_sig_bdd_77) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_166) begin
    if (ap_sig_bdd_166) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_91) begin
    if (ap_sig_bdd_91) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_136) begin
    if (ap_sig_bdd_136) begin
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_159) begin
    if (ap_sig_bdd_159) begin
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_0;
    end
end

always @ (axi_data_V_1_i_reg_171 or p_Val2_s_reg_218 or exitcond_i_reg_359 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond_i_reg_359 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        axi_data_V_1_i_phi_fu_174_p4 = p_Val2_s_reg_218;
    end else begin
        axi_data_V_1_i_phi_fu_174_p4 = axi_data_V_1_i_reg_171;
    end
end

always @ (eol_i_reg_193 or axi_last_V_2_i_reg_205 or exitcond_i_reg_359 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond_i_reg_359 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        eol_i_phi_fu_197_p4 = axi_last_V_2_i_reg_205;
    end else begin
        eol_i_phi_fu_197_p4 = eol_i_reg_193;
    end
end

always @ (eol_reg_160 or axi_last_V_2_i_reg_205 or exitcond_i_reg_359 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond_i_reg_359 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        eol_phi_fu_163_p4 = axi_last_V_2_i_reg_205;
    end else begin
        eol_phi_fu_163_p4 = eol_reg_160;
    end
end

always @ (exitcond_i_reg_359 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_110 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_117 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond_i_reg_359 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        img_data_stream_V_write = ap_const_logic_1;
    end else begin
        img_data_stream_V_write = ap_const_logic_0;
    end
end

always @ (video_in_TVALID or ap_sig_cseq_ST_st2_fsm_1 or exitcond_i_fu_295_p2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or brmerge_i_fu_309_p2 or ap_sig_bdd_110 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_117 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_st7_fsm_5 or ap_sig_bdd_141 or eol_2_i_reg_255) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(video_in_TVALID == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_i_reg_255) & ~ap_sig_bdd_141) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond_i_fu_295_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_i_fu_309_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))))) begin
        video_in_TREADY = ap_const_logic_1;
    end else begin
        video_in_TREADY = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or video_in_TVALID or ap_sig_bdd_65 or exitcond2_i_fu_284_p2 or exitcond_i_fu_295_p2 or ap_sig_bdd_110 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_117 or ap_reg_ppiten_pp1_it1 or ap_sig_bdd_141 or eol_2_i_reg_255 or tmp_user_V_fu_275_p1) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_65) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((~(video_in_TVALID == ap_const_logic_0) & (ap_const_lv1_0 == tmp_user_V_fu_275_p1))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else if ((~(video_in_TVALID == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp_user_V_fu_275_p1))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (~(exitcond2_i_fu_284_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        end
        ap_ST_pp1_stg0_fsm_4 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond_i_fu_295_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond_i_fu_295_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        end
        ap_ST_st7_fsm_5 : 
        begin
            if (((ap_const_lv1_0 == eol_2_i_reg_255) & ~ap_sig_bdd_141)) begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end else if ((~ap_sig_bdd_141 & ~(ap_const_lv1_0 == eol_2_i_reg_255))) begin
                ap_NS_fsm = ap_ST_st8_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end
        end
        ap_ST_st8_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign ap_reg_phiprechg_axi_last_V_2_i_reg_205pp1_it0 = 'bx;

assign ap_reg_phiprechg_p_Val2_s_reg_218pp1_it0 = 'bx;


always @ (ap_CS_fsm) begin
    ap_sig_bdd_102 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end


always @ (exitcond_i_fu_295_p2 or brmerge_i_fu_309_p2) begin
    ap_sig_bdd_109 = ((exitcond_i_fu_295_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_i_fu_309_p2));
end


always @ (video_in_TVALID or exitcond_i_fu_295_p2 or brmerge_i_fu_309_p2) begin
    ap_sig_bdd_110 = ((video_in_TVALID == ap_const_logic_0) & (exitcond_i_fu_295_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_i_fu_309_p2));
end


always @ (img_data_stream_V_full_n or exitcond_i_reg_359) begin
    ap_sig_bdd_117 = ((img_data_stream_V_full_n == ap_const_logic_0) & (exitcond_i_reg_359 == ap_const_lv1_0));
end


always @ (ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_110 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_117 or ap_reg_ppiten_pp1_it1) begin
    ap_sig_bdd_128 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_117 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_136 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end


always @ (video_in_TVALID or eol_2_i_reg_255) begin
    ap_sig_bdd_141 = ((video_in_TVALID == ap_const_logic_0) & (ap_const_lv1_0 == eol_2_i_reg_255));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_159 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_166 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (exitcond_i_fu_295_p2 or brmerge_i_fu_309_p2) begin
    ap_sig_bdd_190 = ((exitcond_i_fu_295_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == brmerge_i_fu_309_p2));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_26 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_start or ap_done_reg) begin
    ap_sig_bdd_65 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_77 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_91 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

assign brmerge_i_fu_309_p2 = (sof_1_i_fu_88 | eol_i_phi_fu_197_p4);

assign exitcond2_i_fu_284_p2 = (p_i_reg_149 == rows? 1'b1: 1'b0);

assign exitcond_i_fu_295_p2 = (p_2_i_reg_182 == cols? 1'b1: 1'b0);

assign i_V_fu_289_p2 = (p_i_reg_149 + ap_const_lv10_1);

assign img_data_stream_V_din = p_Val2_s_reg_218;

assign j_V_fu_300_p2 = (p_2_i_reg_182 + ap_const_lv11_1);

assign tmp_user_V_fu_275_p1 = video_in_TUSER;


endmodule //morphological_filter_AXIvideo2Mat_8_720_1280_0_s

