// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdisparity_pixel_coprocessor.h"

extern XDisparity_pixel_coprocessor_Config XDisparity_pixel_coprocessor_ConfigTable[];

XDisparity_pixel_coprocessor_Config *XDisparity_pixel_coprocessor_LookupConfig(u16 DeviceId) {
	XDisparity_pixel_coprocessor_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDISPARITY_PIXEL_COPROCESSOR_NUM_INSTANCES; Index++) {
		if (XDisparity_pixel_coprocessor_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDisparity_pixel_coprocessor_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDisparity_pixel_coprocessor_Initialize(XDisparity_pixel_coprocessor *InstancePtr, u16 DeviceId) {
	XDisparity_pixel_coprocessor_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDisparity_pixel_coprocessor_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDisparity_pixel_coprocessor_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

