// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xstereo_filter.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XStereo_filter_CfgInitialize(XStereo_filter *InstancePtr, XStereo_filter_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XStereo_filter_Start(XStereo_filter *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStereo_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XStereo_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XStereo_filter_IsDone(XStereo_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStereo_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XStereo_filter_IsIdle(XStereo_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStereo_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XStereo_filter_IsReady(XStereo_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStereo_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XStereo_filter_EnableAutoRestart(XStereo_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XStereo_filter_DisableAutoRestart(XStereo_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XStereo_filter_Set_rows(XStereo_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XStereo_filter_Get_rows(XStereo_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStereo_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XStereo_filter_Set_cols(XStereo_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XStereo_filter_Get_cols(XStereo_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStereo_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XStereo_filter_InterruptGlobalEnable(XStereo_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_GIE, 1);
}

void XStereo_filter_InterruptGlobalDisable(XStereo_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_GIE, 0);
}

void XStereo_filter_InterruptEnable(XStereo_filter *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XStereo_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_IER);
    XStereo_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XStereo_filter_InterruptDisable(XStereo_filter *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XStereo_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_IER);
    XStereo_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XStereo_filter_InterruptClear(XStereo_filter *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XStereo_filter_InterruptGetEnabled(XStereo_filter *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XStereo_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_IER);
}

u32 XStereo_filter_InterruptGetStatus(XStereo_filter *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XStereo_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_FILTER_CONTROL_BUS_ADDR_ISR);
}

