// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xstereo_filter.h"

extern XStereo_filter_Config XStereo_filter_ConfigTable[];

XStereo_filter_Config *XStereo_filter_LookupConfig(u16 DeviceId) {
	XStereo_filter_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSTEREO_FILTER_NUM_INSTANCES; Index++) {
		if (XStereo_filter_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XStereo_filter_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XStereo_filter_Initialize(XStereo_filter *InstancePtr, u16 DeviceId) {
	XStereo_filter_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XStereo_filter_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XStereo_filter_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

