// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSTEREO_FILTER_H
#define XSTEREO_FILTER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xstereo_filter_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XStereo_filter_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XStereo_filter;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XStereo_filter_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XStereo_filter_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XStereo_filter_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XStereo_filter_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XStereo_filter_Initialize(XStereo_filter *InstancePtr, u16 DeviceId);
XStereo_filter_Config* XStereo_filter_LookupConfig(u16 DeviceId);
int XStereo_filter_CfgInitialize(XStereo_filter *InstancePtr, XStereo_filter_Config *ConfigPtr);
#else
int XStereo_filter_Initialize(XStereo_filter *InstancePtr, const char* InstanceName);
int XStereo_filter_Release(XStereo_filter *InstancePtr);
#endif

void XStereo_filter_Start(XStereo_filter *InstancePtr);
u32 XStereo_filter_IsDone(XStereo_filter *InstancePtr);
u32 XStereo_filter_IsIdle(XStereo_filter *InstancePtr);
u32 XStereo_filter_IsReady(XStereo_filter *InstancePtr);
void XStereo_filter_EnableAutoRestart(XStereo_filter *InstancePtr);
void XStereo_filter_DisableAutoRestart(XStereo_filter *InstancePtr);

void XStereo_filter_Set_rows(XStereo_filter *InstancePtr, u32 Data);
u32 XStereo_filter_Get_rows(XStereo_filter *InstancePtr);
void XStereo_filter_Set_cols(XStereo_filter *InstancePtr, u32 Data);
u32 XStereo_filter_Get_cols(XStereo_filter *InstancePtr);

void XStereo_filter_InterruptGlobalEnable(XStereo_filter *InstancePtr);
void XStereo_filter_InterruptGlobalDisable(XStereo_filter *InstancePtr);
void XStereo_filter_InterruptEnable(XStereo_filter *InstancePtr, u32 Mask);
void XStereo_filter_InterruptDisable(XStereo_filter *InstancePtr, u32 Mask);
void XStereo_filter_InterruptClear(XStereo_filter *InstancePtr, u32 Mask);
u32 XStereo_filter_InterruptGetEnabled(XStereo_filter *InstancePtr);
u32 XStereo_filter_InterruptGetStatus(XStereo_filter *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
