// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xstereo_matcher.h"

extern XStereo_matcher_Config XStereo_matcher_ConfigTable[];

XStereo_matcher_Config *XStereo_matcher_LookupConfig(u16 DeviceId) {
	XStereo_matcher_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSTEREO_MATCHER_NUM_INSTANCES; Index++) {
		if (XStereo_matcher_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XStereo_matcher_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XStereo_matcher_Initialize(XStereo_matcher *InstancePtr, u16 DeviceId) {
	XStereo_matcher_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XStereo_matcher_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XStereo_matcher_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

