// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xstereo_matcher.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XStereo_matcher_CfgInitialize(XStereo_matcher *InstancePtr, XStereo_matcher_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XStereo_matcher_Start(XStereo_matcher *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XStereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XStereo_matcher_IsDone(XStereo_matcher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XStereo_matcher_IsIdle(XStereo_matcher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XStereo_matcher_IsReady(XStereo_matcher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XStereo_matcher_EnableAutoRestart(XStereo_matcher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XStereo_matcher_DisableAutoRestart(XStereo_matcher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XStereo_matcher_Set_rows(XStereo_matcher *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XStereo_matcher_Get_rows(XStereo_matcher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XStereo_matcher_Set_cols(XStereo_matcher *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XStereo_matcher_Get_cols(XStereo_matcher *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XStereo_matcher_InterruptGlobalEnable(XStereo_matcher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_GIE, 1);
}

void XStereo_matcher_InterruptGlobalDisable(XStereo_matcher *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_GIE, 0);
}

void XStereo_matcher_InterruptEnable(XStereo_matcher *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XStereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_IER);
    XStereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XStereo_matcher_InterruptDisable(XStereo_matcher *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XStereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_IER);
    XStereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XStereo_matcher_InterruptClear(XStereo_matcher *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStereo_matcher_WriteReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XStereo_matcher_InterruptGetEnabled(XStereo_matcher *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XStereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_IER);
}

u32 XStereo_matcher_InterruptGetStatus(XStereo_matcher *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XStereo_matcher_ReadReg(InstancePtr->Control_bus_BaseAddress, XSTEREO_MATCHER_CONTROL_BUS_ADDR_ISR);
}

